import { Suspense } from 'react';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

import '@/app/globals.css';

import Loading from '@/components/ui/Loading';
import { UserProvider } from '@/contexts/UserContext';

import Providers from '@/app/providers';

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-openSans',
});

export const metadata: Metadata = {
  title: 'ACMS',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Suspense fallback={<Loading />}>
          <Providers>N
            <UserProvider>{children}</UserProvider>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
